# Generated by Django 3.0.5 on 2020-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
