# Generated by Django 3.0.7 on 2020-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('insurance_type', models.CharField(choices=[('1', 'Motor Insurance'), ('2', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
