# Generated by Django 3.0.7 on 2020-07-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
    ]
