# Generated by Django 3.0.5 on 2020-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Policy', '0002_delete_registrationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Insurance_type', models.CharField(choices=[('Motor Insurance', 'Motor Insurance'), ('Other', 'Other')], max_length=16)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=100)),
                ('Estimated_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
