# Generated by Django 3.0.5 on 2020-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0003_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Price', models.CharField(max_length=100)),
                ('Estimated_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
