# Generated by Django 3.0.5 on 2020-07-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0004_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='Estimated_amount',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='Price',
        ),
    ]
